pub mod achievements;
pub mod base_class;
pub mod bot;
pub mod console;
pub mod db;
pub mod diag;
pub mod ffi;
pub mod linked_items;
pub mod log_sink;
pub mod logger;
pub mod loot;
pub mod profile;
pub mod quest;
pub mod ragfair;
pub mod raid;
pub mod runtime;
pub mod scav_case;
pub mod verify;
pub mod weather;

pub const ABI_VERSION: u32 = 37;
